# Lesson 3: Basic Math and Statistics

In [3]:
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
import scipy as sc
import sklearn as sk

from numpy.random import randn
from pandas import Series, DataFrame
from matplotlib import rcParams
from scipy.stats.stats import pearsonr
from scipy.stats import chi2_contingency, spearmanr
from sklearn import preprocessing
from sklearn.preprocessing import scale

In [4]:
%matplotlib inline
rcParams['figure.figsize'] = 8,4
plt.style.use('seaborn-whitegrid')

In [5]:
np.set_printoptions(precision=2)

### A. Perform Arithmetic Operations on Data Using NumPy

In [6]:
#creating 1 dim arrays via a list
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
#creating 2 dim arrays via a list
b = np.array([[1,2,3,4,5,],[10,9,8,7,6,]])
b

array([[ 1,  2,  3,  4,  5],
       [10,  9,  8,  7,  6]])

In [8]:
#Creating arrays via assignments
np.random.seed(25)
c = 12*np.random.randn(6)
c

array([  2.74,  12.32, -10.08,  -7.09, -11.48,  -2.67])

In [9]:
data_address = 'C:/Users/Arthur/python-learning/mtcars.csv'
data_cars = pd.read_csv(data_address)
data_cars.head()

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [13]:
#Creating arrays via assignments and arange function
d = np.arange(1,16)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [16]:
#Performing arthimetic on arrays
aa = np.array([[1,2,3],[2,4,6],[7,5,3]])
aa

array([[1, 2, 3],
       [2, 4, 6],
       [7, 5, 3]])

In [20]:
bb = np.array([[0,4,8],[2,1,0],[5,3,1]])
bb

array([[0, 4, 8],
       [2, 1, 0],
       [5, 3, 1]])

In [21]:
#Performing scalar multiplaction on arrays
cc = aa*bb
cc

array([[ 0,  8, 24],
       [ 4,  4,  0],
       [35, 15,  3]])

In [22]:
dd = bb*aa
dd

array([[ 0,  8, 24],
       [ 4,  4,  0],
       [35, 15,  3]])

In [23]:
#Performing scalar exponentiation on arrays
ee = bb**aa
ee

array([[    0,    16,   512],
       [    4,     1,     0],
       [78125,   243,     1]], dtype=int32)

In [26]:
#Performing dot multiplaction on arrays NOTE that position is important
ff = np.dot(aa,bb)
ff

array([[19, 15, 11],
       [38, 30, 22],
       [25, 42, 59]])

In [28]:
gg = np.dot(bb,aa)
gg

array([[64, 56, 48],
       [ 4,  8, 12],
       [18, 27, 36]])